### ISSUE TITLE
Order to include plugin ?

### ISSUE THREAD

**Issue by Mexflubber** [titancat/postcss-define-function#2]
Hi,

I have the following plugins. In which order should I add them to postcss to make it work?

postcss-define-function
postcss-mixins
postcss-simple-vars
postcss-imports
postcss-nested

In some of my mixins I want to call a function. Is this possible ?

**Comment by mcattx** [comment]
@Mexflubber 
You can refer to the [official documentation](https://github.com/postcss/postcss#usage) to solve your problem.

1.  Use npm to install the plugins you need
2.  Find and add PostCSS extensions for your build tool. (Different build tools have different orders and usage.)
3. Add plugins to your PostCSS process

I hope that the above content can help you.
