### ISSUE TITLE
can not use "postcss-nested" ?

### ISSUE THREAD

**Issue by Hilbertangers** [titancat/postcss-define-function#3]
![image](https://user-images.githubusercontent.com/21299424/60658816-912d9280-9e86-11e9-9dfe-f834cdb8e244.png)
![image](https://user-images.githubusercontent.com/21299424/60658837-9c80be00-9e86-11e9-9bde-f8d2da3bda73.png)

**Comment by mcattx** [comment]
@Hilbertangers Can I have your webpack config file to reappear the issue ?

**Comment by Hilbertangers** [comment]
![image](https://user-images.githubusercontent.com/21299424/60693982-fc22ac00-9f0e-11e9-9873-ccb9a02e204d.png)
@titancat

**Comment by mcattx** [comment]
@Hilbertangers I have reappeared this issue, I need some time to fix it.
ps: Your PR is welcome

**Comment by Hilbertangers** [comment]
Sorry, I can't give pr because I haven't written a postcss plugin, but I think you need to delete the `@callFn` statement, maybe you can get inspiration from [postcss-functions](https://github.com/andyjansson/postcss-functions) @titancat

**Comment by mcattx** [comment]
@Hilbertangers 
You're right.😁
I made some tests a while ago, the reason for the issue is that **postcss-nested** does not recognize `@callFn` keyword.
Maybe I should try another implementation.Thanks for your advice

**Comment by equinusocio** [comment]
Have you tried to define `postcss-define-function` before `postcss-nested`? By this way the nested plugin will get the output css

**Comment by mcattx** [comment]
@Hilbertangers Please try the method mentioned by @equinusocio ?
